image: node:8

# uses new npm ci command
before_script: 
  - npm install

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths: 
  - node_modules/

test:lint:
  script:
    - npm run lint

test:
  script:
    - npm ci
    - npm run build
    - npm test

publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
  artifacts: 
    paths:
      - dist