image: node:8

# uses new npm ci command
before_script: 
  - npm install

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths: 
  - node_modules/

test:lint:
  script:
    - npm run lint

test:
  script:
    - npm install
    - npm run build
    - npm test

publish:artifacts:
  stage: deploy
  only:
    - master
  script:
    - npm run build
  artifacts: 
    name: "optinout.js - $CI_COMMIT_REF_NAME"
    paths:
      - src
      - dist

publish:npm:
  stage: deploy
  only: 
    - /^v-.*$/
  script:
    - npm run build
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - npm publish